### ISSUE TITLE
badges are not updating

### ISSUE THREAD

**Issue by golamSaroar** [puf17640/git-badges#19] opened 2020-08-28 10:38 UTC
Hi, the badges are not updating for some reason. I created repositories, made commits, etc but only the old count is shown. I cleared the cache and also tried in incognito mode, the same result.
Interestingly though, when I open the README file on vscode, and preview the file, I see the updated counts. 
Can you help with this? Below is the code I used to add the badges on my README.md:

```
<a href="https://github.com/golamSaroar?tab=repositories"><img src="https://badges.pufler.dev/repos/golamsaroar"></a>
<a href="https://gist.github.com/golamSaroar"><img src="https://badges.pufler.dev/gists/golamsaroar"></a>
<img src="https://badges.pufler.dev/commits/monthly/golamsaroar">
<a href="https://github.com/golamSaroar/golamsaroar"><img src="https://badges.pufler.dev/updated/golamsaroar/golamsaroar"></a>
```

Thanks.

**Comment by puf17640** [comment] 2020-08-28 11:42
this may be because of the cache policy, I will play around with that a bit and try to make it work better!! thanks for telling me

**Comment by puf17640** [comment] 2020-08-31 10:26
removed cache policy for the badges that don't need it (every one but the visits badge) so this should be fixed

**Comment by golamSaroar** [comment] 2020-08-31 10:47
Could you regenerate the bug? And did you test the fix? Because it didn't work. I just created a gist, still, the old count is shown.

**Comment by puf17640** [comment] 2020-08-31 11:06
> Could you regenerate the bug? And did you test the fix? Because it didn't work. I just created a gist, still, the old count is shown.

I could reproduce it with the commits badge, and tested it afterwards. it might be that githubs internal cache policy for images fucks us over here, any ideas?

**Comment by golamSaroar** [comment] 2020-09-01 04:32
@puf17640 I think it's probably not a cache related issue on GitHub's end. If you look at my README, you'll see I have a "followers" badge, that one is using shields.io and being updated.

**Comment by golamSaroar** [comment] 2020-09-01 04:35
> I could reproduce it with the commits badge, and tested it afterwards. it might be that githubs internal cache policy for images fucks us over here, any ideas?

@puf17640 I think it's probably not a cache related issue on GitHub's end. If you look at my README, you'll see I have a "followers" badge, that one is using shields.io and being updated.

**Comment by deep5050** [comment] 2020-09-04 16:08
> > I could reproduce it with the commits badge, and tested it afterwards. it might be that githubs internal cache policy for images fucks us over here, any ideas?
> 
> @puf17640 I think it's probably not a cache related issue on GitHub's end. If you look at my README, you'll see I have a "followers" badge, that one is using shields.io and being updated.

It might help 
https://github.blog/2010-11-13-sidejack-prevention-phase-3-ssl-proxied-assets/

**Comment by puf17640** [comment] 2020-09-06 11:13
I have now changed the code so that you are actually redirected to shields.io instead of me proxying the shields.io request, this was quite a performance increase and should also have fixed the problem displayed here, since i now have nothing to do with the caching, its all github or shields.io

**Closed by puf17640** 2020-09-06 11:13 UTC

**Comment by minji-o-j** [comment] 2020-09-27 18:38
@puf17640 
Hello I think this problem is still not fixed yet because...

```
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=black&logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000&logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000 &logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000  &logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000&logo=github ">
```  
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=black&logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000&logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000 &logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000  &logo=github"> 
<img src="https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=000000&logo=github ">

<br>

In my computer, the counter seem like  
![image](https://user-images.githubusercontent.com/45448731/94372726-1ca1dc00-013b-11eb-86bb-10b522374b2b.png)

And if I want to update the count of "commits this month", I had to change the link..



But when I visit this link: https://badges.pufler.dev/commits/monthly/minji-o-j?style=flat-square&color=black&logo=github
![image](https://user-images.githubusercontent.com/45448731/94372795-c7b29580-013b-11eb-8644-ee3102d96921.png)

it works well!!

I think it isn't update automatically in markdown file, not only this but Repos badge..

**Comment by puf17640** [comment] 2020-09-27 18:41
yeah it seems that github is the problem here

> ... since i now have nothing to do with the caching, its all github or shields.io

**Comment by nitianabhigyan** [comment] 2022-04-28 06:29
Hi, this maybe useful.
SO after reading through : [https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache) 
There is an option to PURGE the images from GitHub cache and FORCE reload. i.e. 
`curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....`

For anyone facing this, please give it a shot
